### ISSUE TITLE
Where is imgui.h and imgui-SFML.h ?

### ISSUE THREAD

**Issue by AlzoxX76** [yyamDev/ld38#1]
I was go to read your code, but i findn't imgui.h in your include files (in main.cpp), sorry for my english i'm french.

**Comment by yyamDev** [comment]
Hey Alzox76. imgui is a gui library that this project uses. See:
https://github.com/ocornut/imgui
https://github.com/eliasdaler/imgui-sfml

I didn't include these in the repo because they're not really part of the code to the game.
imgui.h is from the original library, imgui-SFML.h is the header to make it work with SFML.
You'll probably need the imgui .cpp files too.

Let me know if you need anything else, I appreciate the interest in my game!

**Comment by AlzoxX76** [comment]
Thank you, I will inquire about this.

You're welcome, I love programming in C++ and I would like to learn and review the structure of video game codes because I do not feel good enough in this area. I see you on Youtube and i find your github in a small instant of your video lol. I read (in french) "think in C++", I ending to read the first volume. I'm in holiday so I don't have time and tool for programming. Good night ! (and alway sorry for my english xD)

**Comment by yyamDev** [comment]
If you want to learn game programming, here is a tutorial series I used when I was first starting:
http://lazyfoo.net/tutorials/SDL/
It assumes you already know how to create c++ console applications. So I'd recommend learning pure c++ first before jumping in to those tutorials.

**Comment by AlzoxX76** [comment]
I have read your code, it's simple and effective.

I think I know quite a lot the basics of C ++. I created my games with the SFML library. I made 3 games:
A snake
A pong
And a game where you have to jump to avoid obstacles (I created a hack for this games via the WINAPI)

I tried to create a fake std :: vector:

`template<class T>
class myVector {
 
    size_t m_nextPos;
    size_t m_sizeData;
    size_t m_sizeBlocAdd;
    const size_t m_sizeTypeVar = sizeof(T);
    T *m_data;
 
    void augmentation(size_t const& _augment) {
        // Pas besoin de vérifier la positivité de _augment car il est non signé
        T *newEspace = new T[m_sizeData + _augment]; // Nouvelle espace allouer
        for (unsigned int i = 0; i < m_sizeData; i++)    // Copie de l'ancien espace sur le nouveau...
            newEspace[i] = m_data[i];                                   // Plus grand
        delete[] m_data; // Supression de l'ancienne espace
        m_data = newEspace; // Changement de l'addresse de la data
        m_sizeData = m_sizeData + _augment; // Augmentation de la taille de la data
    }
 
public:
 
    myVector(size_t _sizeDefault = 100, size_t _sizeBlocAdd = 100) : m_nextPos(0), m_sizeData(0), m_sizeBlocAdd(_sizeBlocAdd), m_data(nullptr) {
        augmentation(_sizeDefault); // Augmentation de la data pour les premieres utilisation
    }
 
    ~myVector() {
        delete[] m_data; // Supressiond de la data
    }
 
    size_t size(void) const {
        return m_nextPos; // Retourne la taille de la data
    }
 
    void clear(void) {
        delete[] m_data; // Supression des donners
        m_data = nullptr; // Pointeur sur null
        m_sizeData = 0; // Reset des variables
        m_nextPos = 0; // contenant des donners sur m_data
        augmentation(m_sizeBlocAdd); // Ajout d'un bloc de data
    }
 
    void reserve(size_t const& _sizeReserve) {
        if (m_sizeData - _sizeReserve > 0) // Reservation de la memoire
            augmentation(_sizeReserve); // Si _sizeReserve est assez grand
    }
 
    void setSizeBloc(size_t _sizeBlocAdd) {
        m_sizeBlocAdd = _sizeBlocAdd; // Set la size des blocs de data à ajouter
    }
 
    void erase(size_t const& _index) {
        if (_index < m_nextPos) { // Si _index est valide
            for (size_t i = _index; i < m_nextPos - 1; i++)// On effectue un decallage
                m_data[i] = m_data[i + 1]; // vers la gauche des éléments
            m_nextPos--; // On decremente la prochaine position
        }
    }
 
    void erase(size_t const& _first, size_t _last) {
        _last++; // Increm. pour suprimer l'element à l'index _last
        if (_last < m_nextPos) { // Si les arguments sont valide
            for (size_t i = _first; i < m_nextPos - 1; i++) // On effectue un decallage
                m_data[i] = m_data[i + (_last - _first)]; // vers la gauche des éléments sans reset
            m_nextPos -= _last - _first; // On soustrait la prochaine position
        }
    }
 
    void pop_back() {
        m_nextPos--; // Suprime le dernier élements (Vas remplacer l'élements à la prochaine insertion)
    }
 
    T &operator[](size_t const& _index) {
        return m_data[_index];  // On renvoie la valeur à _index on ne verifie pas la validité de _index on laisse l'utilisateur gérer
    }
 
    int push_back(T _val) {
        if (m_nextPos >= m_sizeData) // Si il n'y a plus de place on augmente la data size
            augmentation(m_sizeBlocAdd);
        m_data[m_nextPos++] = _val; // Reinterpretation du pointeur de uchar en type demander puis accés au tableaux dynamique
        return (m_nextPos - 1); // Retourne l'index de la valeur insserer
    }
 
};`

but he haven't iterator object. (Sorry the comment in this code was french).
I go read you recommend !
